#!/usr/bin/env node
import { PACKAGE_JSON } from './config/consts.js';
import { runCli } from './utils/cli.js';
import type { CommandRegistry } from './utils/command-registry.js';

const commandRegistry: CommandRegistry = {
  'app create': () => import('./commands/app/create.js'),
  'app delete': () => import('./commands/app/delete.js'),
  'app get': () => import('./commands/app/get.js'),
  'app list': () => import('./commands/app/list.js'),
  'app transfer': () => import('./commands/app/transfer.js'),
  'app update': () => import('./commands/app/update.js'),
  'audience get': () => import('./commands/audience/get.js'),
  'audit-log list': () => import('./commands/audit-log/list.js'),
  'billing get': () => import('./commands/billing/get.js'),
  'billing update': () => import('./commands/billing/update.js'),
  'binary create': () => import('./commands/binary/create.js'),
  'binary get': () => import('./commands/binary/get.js'),
  'binary list': () => import('./commands/binary/list.js'),
  'bundle delete': () => import('./commands/bundle/delete.js'),
  'bundle get': () => import('./commands/bundle/get.js'),
  'bundle list': () => import('./commands/bundle/list.js'),
  'bundle upload': () => import('./commands/bundle/upload.js'),
  'channel create': () => import('./commands/channel/create.js'),
  'channel delete': () => import('./commands/channel/delete.js'),
  'channel get': () => import('./commands/channel/get.js'),
  'channel list': () => import('./commands/channel/list.js'),
  'channel pause': () => import('./commands/channel/pause.js'),
  'channel resume': () => import('./commands/channel/resume.js'),
  'channel update': () => import('./commands/channel/update.js'),
  'checkout create': () => import('./commands/checkout/create.js'),
  'customer-portal-session create': () =>
    import('./commands/customer-portal-session/create.js'),
  'device delete': () => import('./commands/device/delete.js'),
  'device get': () => import('./commands/device/get.js'),
  'device list': () => import('./commands/device/list.js'),
  'device probe': () => import('./commands/device/probe.js'),
  'doctor': () => import('./commands/doctor.js'),
  'fingerprint': () => import('./commands/fingerprint.js'),
  'fingerprint diff': () => import('./commands/fingerprint/diff.js'),
  'init': () => import('./commands/init.js'),
  'limit get': () => import('./commands/limit/get.js'),
  'limit list': () => import('./commands/limit/list.js'),
  'login': () => import('./commands/login.js'),
  'logout': () => import('./commands/logout.js'),
  'open': () => import('./commands/open.js'),
  'organization create': () => import('./commands/organization/create.js'),
  'organization delete': () => import('./commands/organization/delete.js'),
  'organization get': () => import('./commands/organization/get.js'),
  'organization list': () => import('./commands/organization/list.js'),
  'organization update': () => import('./commands/organization/update.js'),
  'release create': () => import('./commands/release/create.js'),
  'release get': () => import('./commands/release/get.js'),
  'release list': () => import('./commands/release/list.js'),
  'release pause': () => import('./commands/release/pause.js'),
  'release resume': () => import('./commands/release/resume.js'),
  'release revoke': () => import('./commands/release/revoke.js'),
  'release rollback': () => import('./commands/release/rollback.js'),
  'release rollout': () => import('./commands/release/rollout.js'),
  'release update': () => import('./commands/release/update.js'),
  'resource-file write': () => import('./commands/resource-file/write.js'),
  'signing-key add': () => import('./commands/signing-key/add.js'),
  'signing-key create': () => import('./commands/signing-key/create.js'),
  'signing-key delete': () => import('./commands/signing-key/delete.js'),
  'signing-key list': () => import('./commands/signing-key/list.js'),
  'statistics get': () => import('./commands/statistics/get.js'),
  'whoami': () => import('./commands/whoami.js'),
};

process.exitCode = await runCli(
  commandRegistry,
  process.argv.slice(2),
  PACKAGE_JSON,
);
